### ISSUE TITLE
Use reqwest 0.10

### ISSUE THREAD

**Issue by brunt** [jgrillo/forecast-rs#18]
Reqwest has been updated to 0.10 to include `async`/`await` support.

Currently `ApiClient::new()` requires a `reqwest::client::Client`, but as of Reqwest 0.10 the Client import path has changed to `reqwest::async_impl::client::Client`. Since a `Client` must be created and passed in to `new()`, it requires that my binary imports `reqwest = "0.9"` if I want to use this crate.

**Comment by jgrillo** [comment]
Thanks @brunt. I have been meaning to go through and update this repo and cut a release, just haven't gotten to it yet. I will try to get to this within the next week.
