### ISSUE TITLE
Dark Sky now part of apple and will shutdown API by the end of 2021

### ISSUE THREAD

**Issue by ParadoxSpiral** [jgrillo/forecast-rs#20]
Unfortunately I just learned of this [post](https://blog.darksky.net/dark-sky-has-a-new-home/). It is unsure whether they will provide a different API (probably not).

Given this, what is the future of forecast-rs?
An option would be to switch providers to e.g. [open weather map](https://openweathermap.org/api).

**Comment by jgrillo** [comment]
Very disappointing news. I think the future of this particular crate is that once the API is dead it'll be yanked from crates.io and the Github repo archived. I don't think it would make sense to make this client work with a different API, instead it would be better to write a client specific to that API. That sounds like a project for someone else :)
